import { useCallback, useEffect, useMemo, useRef, useState, type FormEvent, type ReactNode } from 'react';
import { api } from './api';
import { decodeBase64, encodeBase64, Tier2AudioLink } from './audio-link';
import { OperationsMap } from './OperationsMap';
import type { Campaign, Incident, Overview, PacketStreamItem, RegionalRecord, Responder, SectionKey } from './types';

const NAV: readonly { key: SectionKey; label: string; note: string }[] = [
  { key: 'coordinate', label: 'Coordinate', note: 'Incidents + response' },
  { key: 'publish', label: 'Publish', note: 'Centres + mesh state' },
  { key: 'campaigns', label: 'Campaigns', note: 'Approve + broadcast' },
  { key: 'network', label: 'Packet network', note: 'Mesh + gateway + radio' },
];

export function App() {
  const [section, setSection] = useState<SectionKey>('coordinate');
  const [overview, setOverview] = useState<Overview>();
  const [incidents, setIncidents] = useState<Incident[]>([]);
  const [responders, setResponders] = useState<Responder[]>([]);
  const [records, setRecords] = useState<RegionalRecord[]>([]);
  const [campaigns, setCampaigns] = useState<Campaign[]>([]);
  const [packets, setPackets] = useState<PacketStreamItem[]>([]);
  const [notice, setNotice] = useState<{ text: string; error?: boolean }>();
  const [loading, setLoading] = useState(true);
  const refreshing = useRef(false);

  const refresh = useCallback(async () => {
    if (refreshing.current) return;
    refreshing.current = true;
    try {
      const result = await Promise.all([api.overview(), api.incidents(), api.responders(), api.records(), api.campaigns(), api.packets()]);
      setOverview(result[0]); setIncidents(result[1]); setResponders(result[2]); setRecords(result[3]); setCampaigns(result[4]); setPackets(result[5]);
    } catch (reason) { setNotice({ text: errorText(reason), error: true }); }
    finally { refreshing.current = false; setLoading(false); }
  }, []);

  useEffect(() => { void refresh(); const timer = window.setInterval(() => void refresh(), 3_000); return () => window.clearInterval(timer); }, [refresh]);
  const perform = useCallback(async (label: string, action: () => Promise<unknown>) => {
    setNotice({ text: `${label}…` });
    try { await action(); await refresh(); setNotice({ text: `${label} complete` }); }
    catch (reason) { setNotice({ text: errorText(reason), error: true }); }
  }, [refresh]);

  return <div className="app-shell">
    <a className="skip-link" href="#workspace">Skip to workspace</a>
    <aside className="sidebar">
      <div className="brand-mark"><span>NDON</span><i /></div>
      <div className="product-name"><strong>National Disaster<br />Operations Network</strong><span>Assam deployment · IN-AS</span></div>
      <nav aria-label="Primary operations">{NAV.map((item, index) => <button key={item.key} className={section === item.key ? 'nav-item active' : 'nav-item'} onClick={() => setSection(item.key)}><b>0{index + 1}</b><span><strong>{item.label}</strong><small>{item.note}</small></span></button>)}</nav>
      <div className="sidebar-status"><span className="live-dot" /><div><strong>Operations connected</strong><small>SQLite ledger · 3s live sync</small></div></div>
    </aside>
    <main id="workspace">
      <header className="topbar"><div><span className="jurisdiction">National system / Current deployment</span><h1>{NAV.find((item) => item.key === section)?.label}</h1></div><div className="top-actions"><span className="deployment">ASSAM · IN-AS</span><button className="button ghost" onClick={() => void refresh()}>Sync now</button></div></header>
      {overview && <Metrics overview={overview} packets={packets} />}
      {notice && <div className={notice.error ? 'notice error' : 'notice'} role={notice.error ? 'alert' : 'status'}>{notice.text}<button onClick={() => setNotice(undefined)}>×</button></div>}
      <div className="workspace">{loading ? <Loading /> : section === 'coordinate' ? <Coordinate incidents={incidents} responders={responders} onAssign={(r, i) => perform('Responder assignment', () => api.assign(r, i))} /> : section === 'publish' ? <Publish records={records} packets={packets} onPublish={(id, state) => perform('Mesh publication', () => api.updateRecord(id, state))} /> : section === 'campaigns' ? <CampaignWorkspace campaigns={campaigns} onRefresh={refresh} perform={perform} /> : <PacketNetwork packets={packets} />}</div>
    </main>
  </div>;
}

function Metrics({ overview, packets }: { overview: Overview; packets: PacketStreamItem[] }) {
  return <div className="metrics"><Metric label="Active incidents" value={overview.counts.activeIncidents} tone="danger" /><Metric label="Responders ready" value={overview.counts.availableResponders} /><Metric label="Gateway-ingested" value={packets.filter((p) => p.observations.length > 0).length} /><Metric label="Mesh outbound" value={overview.counts.outboundPackets} /><Metric label="Approved campaigns" value={overview.counts.approvedCampaigns} /></div>;
}
function Metric({ label, value, tone }: { label: string; value: number; tone?: string }) { return <div className={`metric ${tone ?? ''}`}><span>{label}</span><strong>{String(value).padStart(2, '0')}</strong></div>; }

function Coordinate({ incidents, responders, onAssign }: { incidents: Incident[]; responders: Responder[]; onAssign: (responder: string, incident: string) => void }) {
  const [selectedId, setSelectedId] = useState(incidents[0]?.incidentId ?? '');
  const selected = incidents.find((item) => item.incidentId === selectedId) ?? incidents[0];
  return <Page title="Incident command" meta={`${incidents.length} canonical incidents · ${responders.length} responder units`}><div className="command-grid">
    <section className="panel map-panel"><PanelHead title="Operational map" aside="Assam · observed positions" /><OperationsMap incidents={incidents} records={[]} selected={selectedId} onSelect={setSelectedId} /><div className="map-legend"><span><i className="pin critical" />Critical</span><span><i className="pin urgent" />Urgent</span><span><i className="pin facility" />Observed, not inferred</span></div></section>
    <section className="panel incident-panel"><PanelHead title="Incident queue" aside="One row per incident ID" /><div className="data-list">{incidents.map((item) => <button key={item.incidentId} onClick={() => setSelectedId(item.incidentId)} className={selected?.incidentId === item.incidentId ? 'data-row selected' : 'data-row'}><Severity level={item.severity} /><span><strong>{categoryName(item.category)}</strong><small>{item.incidentId}</small></span><span className="align-right"><strong>{item.peopleTotal ?? 0} people</strong><small>{item.observationCount} gateway observations</small></span></button>)}</div></section>
    <section className="panel detail-panel"><PanelHead title="Selected incident" aside={selected?.state ?? 'No selection'} />{selected ? <><div className="incident-title"><Severity level={selected.severity} /><div><h2>{categoryName(selected.category)} assistance</h2><code>{selected.incidentId}</code></div></div><dl className="facts"><Fact label="People" value={String(selected.peopleTotal ?? 0)} /><Fact label="Location age" value={selected.locationAgeS == null ? 'Unknown' : `${selected.locationAgeS}s`} /><Fact label="Accuracy" value={selected.locationAccuracyM == null ? 'Unknown' : `±${selected.locationAccuracyM}m`} /><Fact label="Assigned unit" value={selected.responderRef ?? 'Unassigned'} /></dl><div className="timeline">{selected.timeline.slice().reverse().map((event, i) => <div key={`${event.atS}-${i}`}><i /><span><strong>{event.summary}</strong><small>{formatTimelineSeconds(event.atS)}</small></span></div>)}</div></> : <Empty text="No validated incident packets received." />}</section>
    <section className="panel roster-panel"><PanelHead title="Responder roster" aside="Assign without leaving this page" /><div className="roster">{responders.map((responder) => <div className="roster-row" key={responder.responderRef}><span className={responder.available ? 'unit available' : 'unit busy'}>{responder.name.slice(0, 2).toUpperCase()}</span><div><strong>{responder.name}</strong><small>{responder.district} · {responder.capabilities.join(', ')}</small></div>{responder.available ? <select defaultValue="" onChange={(event) => event.target.value && onAssign(responder.responderRef, event.target.value)} aria-label={`Assign ${responder.name}`}><option value="" disabled>Assign incident</option>{incidents.filter((i) => !['resolved', 'cancelled'].includes(i.state)).map((i) => <option key={i.incidentId} value={i.incidentId}>{categoryName(i.category)} · S{i.severity}</option>)}</select> : <State value={responder.status} />}</div>)}</div></section>
  </div></Page>;
}

function Publish({ records, packets, onPublish }: { records: RegionalRecord[]; packets: PacketStreamItem[]; onPublish: (id: string, state: string) => void }) {
  const [selectedId, setSelectedId] = useState(records[0]?.objectId ?? ''); const selected = records.find((r) => r.objectId === selectedId) ?? records[0]; const [nextState, setNextState] = useState(selected?.state ?? 'open');
  useEffect(() => setNextState(selected?.state ?? 'open'), [selected?.objectId, selected?.state]);
  const related = packets.filter((p) => p.payload.objectId === selected?.objectId || p.outboundRegions.includes('IN-AS'));
  return <Page title="Regional publication" meta="Select a centre, change its state, and publish a canonical packet to the Assam mesh queue"><div className="publish-grid">
    <section className="panel publish-map"><PanelHead title="Centres and operational objects" aside={`${records.length} registered in Assam`} /><OperationsMap incidents={[]} records={records} selected={selectedId} onSelect={setSelectedId} onQuickState={onPublish} /></section>
    <section className="panel publish-control"><PanelHead title="Publication control" aside="Stable compact object ID" />{selected ? <><div className="object-heading"><span className={`object-icon ${selected.kind}`}>{kindGlyph(selected.kind)}</span><div><h2>{selected.name}</h2><p>{selected.district} · {selected.kind}</p><code>{selected.objectId}</code></div></div><label className="control-label">Operational state<select value={nextState} onChange={(e) => setNextState(e.target.value)}>{stateOptions(selected.kind).map((state) => <option key={state}>{state}</option>)}</select></label><div className="publication-impact"><span>On publish</span><p>Version {selected.version + 1} is appended to SQLite, encoded as a Tier 1 packet, and queued for region-bounded gateway delivery.</p></div><button className="button primary full" disabled={nextState === selected.state} onClick={() => onPublish(selected.objectId, nextState)}>Publish state to mesh</button></> : <Empty text="No regional objects registered." />}</section>
    <section className="panel object-register"><PanelHead title="Regional register" aside="Click any row to operate" /><div className="table"><div className="table-row head"><span>Object</span><span>District</span><span>Type</span><span>State</span><span>Version</span></div>{records.map((r) => <button className={r.objectId === selected?.objectId ? 'table-row active' : 'table-row'} key={r.objectId} onClick={() => setSelectedId(r.objectId)}><span><strong>{r.name}</strong><small>{r.objectId}</small></span><span>{r.district}</span><span>{r.kind}</span><span><State value={r.state} /></span><span>v{r.version}</span></button>)}</div></section>
    <section className="panel delivery-panel"><PanelHead title="Delivery evidence" aside="Auto-refreshing packet view" />{related.slice(0, 5).map((packet) => <PacketMini key={packet.packetId} packet={packet} />)}{related.length === 0 && <Empty text="No related packet has been queued or observed yet." />}</section>
  </div></Page>;
}

function CampaignWorkspace({ campaigns, onRefresh, perform }: { campaigns: Campaign[]; onRefresh: () => Promise<void>; perform: (label: string, action: () => Promise<unknown>) => Promise<void> }) {
  const [selectedId, setSelectedId] = useState(campaigns[0]?.campaignId ?? ''); const selected = campaigns.find((c) => c.campaignId === selectedId) ?? campaigns[0];
  return <Page title="Campaign operations" meta="Authority meaning is approved once; broadcast preparation cannot edit it"><CampaignFlow campaign={selected} /><div className="campaign-grid"><CampaignComposer campaigns={campaigns} onSelect={setSelectedId} onCreate={(input) => perform('Campaign draft', () => api.createCampaign(input))} /><section className="panel approval-panel"><PanelHead title="Approval and hand-off" aside={selected?.campaignId ?? 'Select a campaign'} />{selected ? <CampaignApproval campaign={selected} onAction={(state) => perform(`Move campaign to ${state}`, () => api.transitionCampaign(selected.campaignId, state))} onPrepare={() => perform('Acoustic program preparation', () => api.prepareBroadcast(selected.campaignId))} /> : <Empty text="Create a campaign draft to begin." />}</section><section className="panel broadcast-panel"><PanelHead title="Broadcast and receive" aside="Two browsers or decoded WAV" /><BroadcastConsole campaign={selected} onRefresh={onRefresh} /></section></div></Page>;
}
function CampaignFlow({ campaign }: { campaign?: Campaign }) { const steps = ['draft', 'validated', 'approved', 'broadcaster-ready', 'audio-generated', 'decode-tested']; const current = campaign ? Math.max(0, steps.indexOf(campaign.state)) : -1; return <div className="campaign-flow">{steps.map((step, i) => <div key={step} className={i < current ? 'done' : i === current ? 'current' : ''}><i>{i < current ? '✓' : i + 1}</i><span>{flowName(step)}</span></div>)}</div>; }

function CampaignComposer({ campaigns, onCreate, onSelect }: { campaigns: Campaign[]; onCreate: (input: { title: string; summary: string; severity: number; profile: string }) => void; onSelect: (id: string) => void }) {
  const [title, setTitle] = useState('Assam flood safety alert'); const [summary, setSummary] = useState('Move to higher ground and follow district authority instructions.'); const [severity, setSeverity] = useState(2); const submit = (e: FormEvent) => { e.preventDefault(); onCreate({ title, summary, severity, profile: 'audible-normal' }); };
  return <section className="panel composer-panel"><PanelHead title="Campaign register" aside={`${campaigns.length} versions`} /><div className="campaign-list">{campaigns.map((c) => <button key={c.campaignId} onClick={() => onSelect(c.campaignId)}><span><strong>{c.title}</strong><small>{c.campaignId}</small></span><State value={c.state} /></button>)}</div><form className="composer" onSubmit={submit}><h3>New authority message</h3><label>Title<input value={title} onChange={(e) => setTitle(e.target.value)} maxLength={72} required /></label><label>Public instruction<textarea value={summary} onChange={(e) => setSummary(e.target.value)} maxLength={140} required /></label><div className="inline-fields"><label>Severity<select value={severity} onChange={(e) => setSeverity(Number(e.target.value))}><option value="1">Assistance</option><option value="2">Urgent</option><option value="3">Life critical</option></select></label><span>{new TextEncoder().encode(summary).length}/140 bytes</span></div><button className="button primary">Create draft</button></form></section>;
}
function CampaignApproval({ campaign, onAction, onPrepare }: { campaign: Campaign; onAction: (state: string) => void; onPrepare: () => void }) {
  const next = campaign.state === 'draft' ? 'validated' : campaign.state === 'validated' ? 'approved' : campaign.state === 'approved' ? 'broadcaster-ready' : undefined;
  return <div className="approval"><div className="approval-copy"><State value={campaign.state} /><h2>{campaign.title}</h2><p>{campaign.summary}</p></div><dl className="facts"><Fact label="Tier 2 bytes" value={String(campaign.preview.totalTier2Bytes)} /><Fact label="Frames" value={String(campaign.preview.items[0]?.frameCount ?? 0)} /><Fact label="Repetitions" value={`${campaign.preview.items[0]?.repeats ?? 0}×`} /><Fact label="Duration" value={`${campaign.preview.totalDurationS}s`} /></dl>{campaign.approvalDigest && <div className="digest"><span>Immutable approval digest</span><code>{campaign.approvalDigest}</code></div>}<div className="action-line">{next && <button className="button primary" onClick={() => onAction(next)}>{next === 'validated' ? 'Validate packet budget' : next === 'approved' ? 'Approve this exact version' : 'Send to broadcast desk'}</button>}{campaign.state === 'broadcaster-ready' && <button className="button primary" onClick={onPrepare}>Generate WavePX program</button>}</div></div>;
}

function BroadcastConsole({ campaign, onRefresh }: { campaign?: Campaign; onRefresh: () => Promise<void> }) {
  const [mode, setMode] = useState<'send' | 'receive'>('send'); const [state, setState] = useState('Ready'); const [frames, setFrames] = useState<string[]>([]); const [level, setLevel] = useState(0); const [busy, setBusy] = useState(false); const [decoded, setDecoded] = useState(campaign?.decodeResult?.decodedMessage); const link = useRef<Tier2AudioLink>(); const submitted = useRef('');
  useEffect(() => () => link.current?.destroy(), []); useEffect(() => setDecoded(campaign?.decodeResult?.decodedMessage), [campaign?.decodeResult]);
  const program = campaign?.broadcastProgram; const expected = program?.uniqueFramesBase64.length ?? 0;
  const makeLink = (receive = false) => { link.current?.destroy(); const next = new Tier2AudioLink({ onLevel: setLevel, onState: (s) => setState(s === 'listening' ? 'Listening to microphone' : s === 'transmitting' ? 'Broadcasting audio' : s === 'initializing' ? 'Starting WavePX modem' : 'Ready'), onFrame: receive ? (frame) => setFrames((all) => { const encoded = encodeBase64(frame); return all.includes(encoded) ? all : [...all, encoded]; }) : undefined }); link.current = next; return next; };
  const submitReception = useCallback(async (source: 'tier2-mic' | 'tier2-direct') => { if (!campaign || frames.length === 0) return; const key = `${campaign.campaignId}:${frames.join('.')}`; if (submitted.current === key) return; submitted.current = key; setBusy(true); try { const updated = await api.reportReception(campaign.campaignId, frames, source); setDecoded(updated.decodeResult?.decodedMessage); setState(updated.decodeResult?.passed ? 'Exact packet recovered and decoded' : `${updated.decodeResult?.missingFrames ?? 0} expected frame(s) missing`); await onRefresh(); } catch (reason) { setState(errorText(reason)); submitted.current = ''; } finally { setBusy(false); } }, [campaign, frames, onRefresh]);
  useEffect(() => { if (mode === 'receive' && expected > 0 && frames.length >= expected) void submitReception('tier2-mic'); }, [expected, frames.length, mode, submitReception]);
  if (!campaign) return <Empty text="Select a campaign." />; if (!program) return <Empty text="Complete approval and generate the acoustic program to enable transmission." />;
  const transmit = async () => { setBusy(true); try { await makeLink().transmit(program.playbackFramesBase64.map(decodeBase64), program.profile); setState('Broadcast cycle complete'); } catch (reason) { setState(errorText(reason)); } finally { setBusy(false); } };
  const listen = async () => { setFrames([]); submitted.current = ''; try { await makeLink(true).listen(); } catch (reason) { setState(errorText(reason)); } };
  const decodeFile = async (file: File) => { setBusy(true); setFrames([]); submitted.current = ''; try { const recovered = await makeLink().decodeAudioFile(file); const unique = [...new Set(recovered.map(encodeBase64))]; setFrames(unique); const updated = await api.reportReception(campaign.campaignId, unique, 'tier2-direct'); setDecoded(updated.decodeResult?.decodedMessage); setState(updated.decodeResult?.passed ? 'Audio file decoded exactly' : `${updated.decodeResult?.missingFrames ?? 0} frame(s) missing`); await onRefresh(); } catch (reason) { setState(errorText(reason)); } finally { setBusy(false); } };
  const exportWav = async () => { setBusy(true); try { const modem = makeLink(); await modem.init(); const blob = modem.createWav(program.playbackFramesBase64.map(decodeBase64), program.profile); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = `${program.programId}.wav`; a.click(); URL.revokeObjectURL(url); setState('WAV program exported'); } finally { setBusy(false); } };
  return <div className="broadcast-console"><div className="mode-tabs"><button className={mode === 'send' ? 'active' : ''} onClick={() => setMode('send')}>Send audio</button><button className={mode === 'receive' ? 'active' : ''} onClick={() => setMode('receive')}>Receive + decode</button></div><div className="station-state"><span className="live-dot" /><strong>{state}</strong></div>{mode === 'send' ? <><div className="program-strip"><span><small>Program</small><code>{program.programId}</code></span><span><small>Profile</small><strong>{program.profile}</strong></span><span><small>Scheduled</small><strong>{program.playbackFramesBase64.length} frames</strong></span></div><div className="action-line"><button className="button primary" disabled={busy} onClick={() => void transmit()}>Broadcast through speaker</button><button className="button secondary" disabled={busy} onClick={() => void exportWav()}>Export WAV</button></div></> : <><div className="receiver-meter"><i style={{ width: `${Math.min(100, level * 900)}%` }} /></div><strong className="frame-count">{frames.length}/{expected} unique frames</strong><div className="action-line"><button className="button primary" onClick={() => void listen()}>Listen to microphone</button><button className="button ghost" onClick={() => link.current?.stopListening()}>Stop</button><label className="button secondary file-button">Decode WAV<input type="file" accept="audio/*" onChange={(e) => { const file = e.target.files?.[0]; if (file) void decodeFile(file); }} /></label><button className="button secondary" disabled={busy || frames.length === 0} onClick={() => void submitReception('tier2-direct')}>Compare now</button></div>{decoded && <div className="decoded-message"><span>Decoded public message</span><h3>{categoryName(decoded.category)} · Severity {decoded.severity}</h3><p>{decoded.text}</p><dl><Fact label="Campaign" value={decoded.campaignId} /><Fact label="Region" value={decoded.regionCode} /><Fact label="Language" value={decoded.language} /></dl></div>}</>}</div>;
}

function PacketNetwork({ packets }: { packets: PacketStreamItem[] }) {
  const [selectedId, setSelectedId] = useState(packets[0]?.packetId ?? ''); const selected = packets.find((p) => p.packetId === selectedId) ?? packets[0];
  const counts = useMemo(() => ({ mesh: packets.filter((p) => p.direction === 'mesh-local').length, up: packets.filter((p) => p.direction === 'mesh-to-internet').length, down: packets.filter((p) => p.direction === 'internet-to-mesh').length, radio: packets.filter((p) => p.direction === 'radio-to-mesh').length }), [packets]);
  return <Page title="Packet network" meta="The transports stay distinct. A gateway links them without rewriting packet identity or meaning."><div className="network-path"><PathNode title="Bluetooth mesh" count={counts.mesh} sub="Tier 1 · store and forward" /><PathLink label="gateway upload" /><PathNode title="Internet coordination" count={counts.up} sub="validated canonical store" /><PathLink label="regional selection" /><PathNode title="Radio broadcast" count={counts.down} sub="Tier 2 · WavePX/ggwave" /><PathLink label="receiver bridge" /><PathNode title="Mesh re-entry" count={counts.radio} sub="same packet identity" /></div><div className="network-grid"><section className="panel packet-table"><PanelHead title="Live canonical packet stream" aside={`${packets.length} packets · 3s refresh`} /><div className="table packet"><div className="table-row head"><span>Packet / type</span><span>Direction</span><span>Source</span><span>Hops</span><span>Evidence</span></div>{packets.map((p) => <button key={p.packetId} className={selected?.packetId === p.packetId ? 'table-row active' : 'table-row'} onClick={() => setSelectedId(p.packetId)}><span><strong>{p.typeName}</strong><small>{shortId(p.packetId, 16)}</small></span><span><Direction value={p.direction} /></span><span>{p.sourceLabel}</span><span>{p.hopCount}/{p.hopLimit}</span><span>{p.observations.length} gateway · {p.totalBytes} B</span></button>)}</div></section><section className="panel inspector"><PanelHead title="Packet inspector" aside="Raw bytes + decoded fields" />{selected ? <><div className="packet-id"><span>Canonical packet ID</span><code>{selected.packetId}</code></div><dl className="facts"><Fact label="Message type" value={`${selected.typeName} (${selected.type})`} /><Fact label="Family" value={selected.family} /><Fact label="Fragment" value={`${selected.fragmentIndex + 1}/${selected.fragmentCount}`} /><Fact label="Digest" value={selected.digestPrefix} /></dl><h3>Hop and gateway observations</h3>{selected.observations.length ? selected.observations.map((o, i) => <div className="observation" key={`${o.gatewayToken}-${i}`}><i /><span><strong>{o.gatewayToken}</strong><small>{o.transport} · arrived at hop {o.hopCountOnArrival} · {formatDateTime(o.receivedAtMs)}</small></span></div>) : <Empty text="No internet gateway has observed this packet yet." />}<h3>Decoded payload</h3><pre>{JSON.stringify(selected.payload, null, 2)}</pre><h3>Exact canonical bytes</h3><code className="hex">{selected.bytesHex}</code></> : <Empty text="No packets stored." />}</section></div></Page>;
}

function Page({ title, meta, children }: { title: string; meta: string; children: ReactNode }) { return <section className="page"><header className="page-head"><h2>{title}</h2><p>{meta}</p></header>{children}</section>; }
function PanelHead({ title, aside }: { title: string; aside: string }) { return <header className="panel-head"><h3>{title}</h3><span>{aside}</span></header>; }
function Empty({ text }: { text: string }) { return <div className="empty">{text}</div>; }
function Loading() { return <div className="loading"><i /><span>Loading operational ledger</span></div>; }
function Severity({ level }: { level: number }) { return <span className={`severity s${level}`}>S{level}</span>; }
function State({ value }: { value: string }) { return <span className={`state state-${value}`}>{value.replaceAll('-', ' ')}</span>; }
function Fact({ label, value }: { label: string; value: string }) { return <div><dt>{label}</dt><dd>{value}</dd></div>; }
function PacketMini({ packet }: { packet: PacketStreamItem }) { return <button className="packet-mini"><Direction value={packet.direction} /><span><strong>{packet.typeName}</strong><small>{shortId(packet.packetId, 18)}</small></span><span><strong>{packet.totalBytes} B</strong><small>{packet.observations.length} gateway observations</small></span></button>; }
function Direction({ value }: { value: PacketStreamItem['direction'] }) { const label: Record<PacketStreamItem['direction'], string> = { 'mesh-local': 'Mesh local', 'mesh-to-internet': 'Mesh → Internet', 'internet-to-mesh': 'Internet → Mesh', 'radio-to-mesh': 'Radio → Mesh' }; return <span className={`direction ${value}`}>{label[value]}</span>; }
function PathNode({ title, count, sub }: { title: string; count: number; sub: string }) { return <div className="path-node"><strong>{title}</strong><b>{count}</b><small>{sub}</small></div>; }
function PathLink({ label }: { label: string }) { return <div className="path-link"><span>{label}</span><i>→</i></div>; }
function stateOptions(kind: string): string[] { if (kind === 'hazard') return ['active', 'watch', 'cleared']; if (kind === 'route') return ['open', 'restricted', 'blocked']; return ['open', 'full', 'closed', 'damaged']; }
function kindGlyph(kind: string): string { return kind === 'shelter' ? '⌂' : kind === 'medical' ? '+' : kind === 'route' ? '↗' : kind === 'hazard' ? '!' : '●'; }
function categoryName(value: number): string { return ['Medical', 'Trapped', 'Fire', 'Flood', 'Violence', 'Structural collapse', 'Missing person', 'Other'][value] ?? 'Emergency'; }
function flowName(value: string): string { return ({ draft: 'Draft', validated: 'Budget checked', approved: 'Authority approved', 'broadcaster-ready': 'Broadcast desk', 'audio-generated': 'Audio ready', 'decode-tested': 'Reception proven' } as Record<string, string>)[value] ?? value; }
function shortId(value: string, length = 10): string { return value.length > length ? `${value.slice(0, length)}…` : value; }
function formatDateTime(value: number): string { return new Intl.DateTimeFormat('en-IN', { day: '2-digit', month: 'short', hour: '2-digit', minute: '2-digit', second: '2-digit' }).format(value); }
function formatTimelineSeconds(value: number): string { return formatDateTime(Date.UTC(2025, 0, 1) + value * 1000); }
function errorText(reason: unknown): string { return reason instanceof Error ? reason.message : String(reason); }
