/**
 * Per-message-type payload bounds. Checked BEFORE allocation (INT-001).
 * Spec: 02-... "Packet sizing rules", "Performance and resource budgets".
 */

import { MAX_PAYLOAD_BY_CLASS, MessageType } from '@dsm/contracts';

const BY_TYPE: Readonly<Record<number, number>> = {
  [MessageType.SOS_CREATE]: MAX_PAYLOAD_BY_CLASS.EMERGENCY,
  [MessageType.SOS_UPDATE]: MAX_PAYLOAD_BY_CLASS.EMERGENCY,
  [MessageType.SOS_CANCEL]: MAX_PAYLOAD_BY_CLASS.RESPONSE_CONTROL,
  [MessageType.RESPONDER_ASSIGNED]: MAX_PAYLOAD_BY_CLASS.RESPONSE_CONTROL,
  [MessageType.RESPONDER_ACCEPTED]: MAX_PAYLOAD_BY_CLASS.RESPONSE_CONTROL,
  [MessageType.RESPONDER_DECLINED]: MAX_PAYLOAD_BY_CLASS.RESPONSE_CONTROL,
  [MessageType.RESPONDER_EN_ROUTE]: MAX_PAYLOAD_BY_CLASS.RESPONSE_CONTROL,
  [MessageType.RESPONDER_ARRIVED]: MAX_PAYLOAD_BY_CLASS.RESPONSE_CONTROL,
  [MessageType.RESOLVED]: MAX_PAYLOAD_BY_CLASS.RESPONSE_CONTROL,
  [MessageType.LINK_RECEIPT]: MAX_PAYLOAD_BY_CLASS.RECEIPT,
  [MessageType.BACKEND_ACKNOWLEDGEMENT]: MAX_PAYLOAD_BY_CLASS.RECEIPT,
  [MessageType.SHELTER]: MAX_PAYLOAD_BY_CLASS.RESOURCE,
  [MessageType.MEDICAL_POST]: MAX_PAYLOAD_BY_CLASS.RESOURCE,
  [MessageType.FOOD_WATER]: MAX_PAYLOAD_BY_CLASS.RESOURCE,
  [MessageType.SAFE_ZONE]: MAX_PAYLOAD_BY_CLASS.RESOURCE,
  [MessageType.HAZARD]: MAX_PAYLOAD_BY_CLASS.HAZARD_ROUTE,
  [MessageType.ROUTE_STATE]: MAX_PAYLOAD_BY_CLASS.HAZARD_ROUTE,
  [MessageType.OFFICIAL_ALERT]: MAX_PAYLOAD_BY_CLASS.AUTHORITY,
  [MessageType.WEATHER_BULLETIN]: MAX_PAYLOAD_BY_CLASS.AUTHORITY,
  [MessageType.CHECKIN_CAMPAIGN]: MAX_PAYLOAD_BY_CLASS.CHECKIN,
  [MessageType.CHECKIN_RESPONSE]: MAX_PAYLOAD_BY_CLASS.CHECKIN,
  [MessageType.RESOURCE_REQUEST]: MAX_PAYLOAD_BY_CLASS.REQUEST,
  [MessageType.CACHE_CATALOG]: MAX_PAYLOAD_BY_CLASS.CONTENT_OP,
  [MessageType.CONTENT_ACTIVATE]: MAX_PAYLOAD_BY_CLASS.CONTENT_OP,
  [MessageType.RECORD_UPSERT]: MAX_PAYLOAD_BY_CLASS.CONTENT_OP,
  [MessageType.RECORD_TOMBSTONE]: MAX_PAYLOAD_BY_CLASS.CONTENT_OP,
  [MessageType.CACHE_INVALIDATE]: MAX_PAYLOAD_BY_CLASS.CONTENT_OP,
  [MessageType.FILE_MANIFEST]: MAX_PAYLOAD_BY_CLASS.FILE_MANIFEST,
  [MessageType.FILE_FRAGMENT]: MAX_PAYLOAD_BY_CLASS.FILE_FRAGMENT,
  [MessageType.HELLO_CAPABILITY]: MAX_PAYLOAD_BY_CLASS.SESSION_CONTROL,
  [MessageType.INVENTORY]: MAX_PAYLOAD_BY_CLASS.SESSION_CONTROL,
  [MessageType.PACKET_REQUEST]: MAX_PAYLOAD_BY_CLASS.SESSION_CONTROL,
  [MessageType.NETWORK_STATUS_OBSERVATION]: MAX_PAYLOAD_BY_CLASS.CONTENT_OP,
};

export function maxPayloadBytesFor(messageType: number): number {
  return BY_TYPE[messageType] ?? MAX_PAYLOAD_BY_CLASS.CONTENT_OP;
}
